import sqlite3

conn = sqlite3.connect("sessionresults.db")
cursor = conn.cursor()

tables = [
    "Seasons", "GrandsPrix", "Drivers", "Constructors", "Teams",
    "Engines", "Tyres", "Chassis", "EngineModels", "Circuits", "CircuitLayouts",
    "GrandPrixResults", "PitStopSummary", "LapByLap",
    "DriversChampionship", "ConstructorsChampionship",
    "InSeasonProgressDrivers", "InSeasonProgressConstructors", "Nationalities", "RaceReports", "Sessions"
]

for table in tables:
    cursor.execute(f"DROP TABLE IF EXISTS {table}")

# === TABLE CREATION ===

cursor.execute('''CREATE TABLE Seasons (
    Season INTEGER PRIMARY KEY,
    DriversRacesCounted TEXT,
    PointsSharedForSharedCars BOOLEAN,
    GrandPrixPointsSystemDrivers TEXT,
    SprintPointsSystemDrivers TEXT,
    ConstructorsRacesCounted TEXT,
    PointsOnlyForTopScoringCar BOOLEAN,
    GrandPrixPointsSystemConstructors TEXT,
    SprintPointsSystemConstructors TEXT,
    RegulationNotes TEXT,
    MinimumWeightofCars TEXT,
    EngineType TEXT,
    Supercharging TEXT,
    MaxCylinderCapacity TEXT,
    NumberOfCylinders TEXT,
    MaxRPM TEXT,
    NumberOfEnginesAllowedPerSeason TEXT,
    FuelType TEXT,
    RefuellingAllowed TEXT,
    MaxFuelConsumption TEXT,
    TotalGrandPrix INTEGER DEFAULT 0,
    TotalDrivers INTEGER DEFAULT 0,
    TotalConstructors INTEGER DEFAULT 0,
    TotalEngines INTEGER DEFAULT 0,
    TotalTeams INTEGER DEFAULT 0,
    TotalEngineModels INTEGER DEFAULT 0,
    TotalChassis INTEGER DEFAULT 0,
    TotalNationalities INTEGER DEFAULT 0,
    needstatsupdate BOOLEAN DEFAULT 0
)''')

cursor.execute('''CREATE TABLE Circuits (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CircuitName TEXT UNIQUE,
    Latitude REAL,
    Longitude REAL,
    FirstGrandPrix TEXT,
    LastGrandPrix TEXT,
    GrandPrixCount INTEGER DEFAULT 0,
    FirstGrandPrixID INTEGER,
    LastGrandPrixID INTEGER,
    needstatsupdate BOOLEAN DEFAULT 0,
    FOREIGN KEY (FirstGrandPrixID) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (LastGrandPrixID) REFERENCES GrandsPrix(ID)
)''')

cursor.execute('''CREATE TABLE CircuitLayouts (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Latitude REAL,
    Longitude REAL,
    CircuitVersion TEXT,
    FirstGrandPrix TEXT,
    LastGrandPrix TEXT,
    GrandPrixCount INTEGER DEFAULT 0,
    GrandPrixDates TEXT,
    SVG TEXT,
    CircuitChanges TEXT,
    FirstGrandPrixID INTEGER,
    LastGrandPrixID INTEGER,
    needstatsupdate BOOLEAN DEFAULT 0,
    FOREIGN KEY (FirstGrandPrixID) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (LastGrandPrixID) REFERENCES GrandsPrix(ID)
)''')

cursor.execute('''CREATE TABLE Sessions (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    GrandPrix TEXT,
    SessionName TEXT,
    SessionNumber INTEGER,
    WasSessionCancelled BOOLEAN,
    StartTimeTimestampUTC INTEGER,
    EndTimeTimestampUTC INTEGER,
    StartTimeTimestamp INTEGER,
    EndTimeTimestamp INTEGER,
    IfPreciseStartTime BOOLEAN,
    StartTimeinDatetimeUTC TEXT,
    EndTimeinDatetimeUTC TEXT,
    StartTimeinDatetime TEXT,
    EndTimeinDatetime TEXT,
    GrandPrixID INTEGER,
    FOREIGN KEY (GrandPrixID) REFERENCES GrandsPrix(ID)
)''')

cursor.execute('''CREATE TABLE GrandsPrix (
    ID INTEGER PRIMARY KEY,
    Season INTEGER,
    GrandPrixName TEXT,
    RoundNumber INTEGER,
    CircuitName TEXT,
    Date TEXT,
    DateInDateTime TEXT,
    Laps INTEGER,
    PoleSide TEXT,
    GridFormation TEXT,
    CircuitLength TEXT,
    Weather TEXT,
    Notes TEXT,
    SprintWeekend BOOLEAN,
    EntrantsNotes TEXT,
    QualifyingNotes TEXT,
    StartingGridNotes TEXT,
    RaceResultNotes TEXT,
    SprintNotes TEXT,
    SprintGridNotes TEXT,
    CircuitID INTEGER,
    CircuitLayoutID INTEGER,
    needstatsupdate BOOLEAN DEFAULT 0,
    FOREIGN KEY (CircuitID) REFERENCES Circuits(ID)
    FOREIGN KEY (CircuitLayoutID) REFERENCES CircuitLayouts(ID)
)''')

cursor.execute('''CREATE TABLE Drivers (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT UNIQUE,
    Nationality TEXT,
    Birthdate TEXT,
    Wins INTEGER DEFAULT 0,
    Podiums INTEGER DEFAULT 0,
    Poles INTEGER DEFAULT 0,
    FastestLaps INTEGER DEFAULT 0,
    SprintWins INTEGER DEFAULT 0,
    SprintPodiums INTEGER DEFAULT 0,
    SprintPoles INTEGER DEFAULT 0,
    SprintFastestLaps INTEGER DEFAULT 0,
    Championships INTEGER DEFAULT 0,
    SeasonsRaced INTEGER DEFAULT 0,
    Points REAL DEFAULT 0,
    Starts INTEGER DEFAULT 0,
    Entries INTEGER DEFAULT 0,
    SprintStarts INTEGER DEFAULT 0,
    SprintEntries INTEGER DEFAULT 0,
    DNFs INTEGER DEFAULT 0,
    GrandPrixLapsLed INTEGER DEFAULT 0,
    SprintLapsLed INTEGER DEFAULT 0,
    HatTricks INTEGER DEFAULT 0,
    GrandSlams INTEGER DEFAULT 0,
    BestGridPosition INTEGER,
    BestSprintGridPosition INTEGER,
    BestQualifyingPosition INTEGER,
    BestRacePosition INTEGER,
    BestSprintPosition INTEGER,
    BestSprintQualifyingPosition INTEGER,
    BestChampionshipPosition INTEGER,
    FirstGrandPrix TEXT,
    LastGrandPrix TEXT,
    NationalityID INTEGER,
    FirstGrandPrixID INTEGER,
    LastGrandPrixID INTEGER,
    needstatsupdate BOOLEAN DEFAULT 0,
    FOREIGN KEY (NationalityID) REFERENCES Nationalities(ID),
    FOREIGN KEY (FirstGrandPrixID) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (LastGrandPrixID) REFERENCES GrandsPrix(ID)
)''')

cursor.execute('''CREATE TABLE Teams (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TeamName TEXT UNIQUE,
    FirstGrandPrix TEXT,
    LastGrandPrix TEXT,
    Wins INTEGER DEFAULT 0,
    Podiums INTEGER DEFAULT 0,
    Poles INTEGER DEFAULT 0,
    FastestLaps INTEGER DEFAULT 0,
    SprintWins INTEGER DEFAULT 0,
    SprintPodiums INTEGER DEFAULT 0,
    SprintPoles INTEGER DEFAULT 0,
    SprintFastestLaps INTEGER DEFAULT 0,
    SeasonsRaced INTEGER DEFAULT 0,
    Starts INTEGER DEFAULT 0,
    Entries INTEGER DEFAULT 0,
    SprintStarts INTEGER DEFAULT 0,
    SprintEntries INTEGER DEFAULT 0,
    DNFs INTEGER DEFAULT 0,
    GrandPrixLapsLed INTEGER DEFAULT 0,
    SprintLapsLed INTEGER DEFAULT 0,
    Points REAL DEFAULT 0,
    BestGridPosition INTEGER,
    BestSprintGridPosition INTEGER,
    BestQualifyingPosition INTEGER,
    BestRacePosition INTEGER,
    BestSprintPosition INTEGER,
    BestSprintQualifyingPosition INTEGER,
    FirstGrandPrixID INTEGER,
    LastGrandPrixID INTEGER,
    needstatsupdate BOOLEAN DEFAULT 0,
    FOREIGN KEY (FirstGrandPrixID) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (LastGrandPrixID) REFERENCES GrandsPrix(ID)
)''')

cursor.execute('''CREATE TABLE Constructors (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ConstructorName TEXT UNIQUE,
    Wins INTEGER DEFAULT 0,
    Podiums INTEGER DEFAULT 0,
    Poles INTEGER DEFAULT 0,
    FastestLaps INTEGER DEFAULT 0,
    SprintWins INTEGER DEFAULT 0,
    SprintPodiums INTEGER DEFAULT 0,
    SprintPoles INTEGER DEFAULT 0,
    SprintFastestLaps INTEGER DEFAULT 0,
    Championships INTEGER DEFAULT 0,
    SeasonsRaced INTEGER DEFAULT 0,
    Points REAL DEFAULT 0,
    Starts INTEGER DEFAULT 0,
    Entries INTEGER DEFAULT 0,
    SprintStarts INTEGER DEFAULT 0,
    SprintEntries INTEGER DEFAULT 0,
    DNFs INTEGER DEFAULT 0,
    GrandPrixLapsLed INTEGER DEFAULT 0,
    SprintLapsLed INTEGER DEFAULT 0,
    BestGridPosition INTEGER,
    BestSprintGridPosition INTEGER,
    BestQualifyingPosition INTEGER,
    BestRacePosition INTEGER,
    BestSprintPosition INTEGER,
    BestSprintQualifyingPosition INTEGER,
    BestChampionshipPosition INTEGER,
    FirstGrandPrix TEXT,
    LastGrandPrix TEXT,
    FirstGrandPrixID INTEGER,
    LastGrandPrixID INTEGER,
    needstatsupdate BOOLEAN DEFAULT 0,
    FOREIGN KEY (FirstGrandPrixID) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (LastGrandPrixID) REFERENCES GrandsPrix(ID)
)''')

cursor.execute('''CREATE TABLE Engines (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EngineName TEXT UNIQUE,
    Wins INTEGER DEFAULT 0,
    Podiums INTEGER DEFAULT 0,
    Poles INTEGER DEFAULT 0,
    FastestLaps INTEGER DEFAULT 0,
    SprintWins INTEGER DEFAULT 0,
    SprintPodiums INTEGER DEFAULT 0,
    SprintPoles INTEGER DEFAULT 0,
    SprintFastestLaps INTEGER DEFAULT 0,
    Championships INTEGER DEFAULT 0,
    SeasonsRaced INTEGER DEFAULT 0,
    Points REAL DEFAULT 0,
    Starts INTEGER DEFAULT 0,
    Entries INTEGER DEFAULT 0,
    SprintStarts INTEGER DEFAULT 0,
    SprintEntries INTEGER DEFAULT 0,
    DNFs INTEGER DEFAULT 0,
    GrandPrixLapsLed INTEGER DEFAULT 0,
    SprintLapsLed INTEGER DEFAULT 0,
    BestGridPosition INTEGER,
    BestSprintGridPosition INTEGER,
    BestQualifyingPosition INTEGER,
    BestRacePosition INTEGER,
    BestSprintPosition INTEGER,
    BestSprintQualifyingPosition INTEGER,
    FirstGrandPrix TEXT,
    LastGrandPrix TEXT,
    FirstGrandPrixID INTEGER,
    LastGrandPrixID INTEGER,
    needstatsupdate BOOLEAN DEFAULT 0,
    FOREIGN KEY (FirstGrandPrixID) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (LastGrandPrixID) REFERENCES GrandsPrix(ID)
)''')

cursor.execute('''CREATE TABLE Tyres (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TyreName TEXT UNIQUE,
    Wins INTEGER DEFAULT 0,
    Podiums INTEGER DEFAULT 0,
    Poles INTEGER DEFAULT 0,
    FastestLaps INTEGER DEFAULT 0,
    SprintWins INTEGER DEFAULT 0,
    SprintPodiums INTEGER DEFAULT 0,
    SprintPoles INTEGER DEFAULT 0,
    SprintFastestLaps INTEGER DEFAULT 0,
    SeasonsRaced INTEGER DEFAULT 0,
    Points REAL DEFAULT 0,
    Starts INTEGER DEFAULT 0,
    Entries INTEGER DEFAULT 0,
    SprintStarts INTEGER DEFAULT 0,
    SprintEntries INTEGER DEFAULT 0,
    DNFs INTEGER DEFAULT 0,
    GrandPrixLapsLed INTEGER DEFAULT 0,
    SprintLapsLed INTEGER DEFAULT 0,
    BestGridPosition INTEGER,
    BestSprintGridPosition INTEGER,
    BestQualifyingPosition INTEGER,
    BestRacePosition INTEGER,
    BestSprintPosition INTEGER,
    BestSprintQualifyingPosition INTEGER,
    FirstGrandPrix TEXT,
    LastGrandPrix TEXT,
    FirstGrandPrixID INTEGER,
    LastGrandPrixID INTEGER,
    needstatsupdate BOOLEAN DEFAULT 0,
    FOREIGN KEY (FirstGrandPrixID) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (LastGrandPrixID) REFERENCES GrandsPrix(ID)
)''')

cursor.execute('''CREATE TABLE Chassis (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ConstructorName TEXT,
    ChassisName TEXT UNIQUE,
    Wins INTEGER DEFAULT 0,
    Podiums INTEGER DEFAULT 0,
    Poles INTEGER DEFAULT 0,
    FastestLaps INTEGER DEFAULT 0,
    SprintWins INTEGER DEFAULT 0,
    SprintPodiums INTEGER DEFAULT 0,
    SprintPoles INTEGER DEFAULT 0,
    SprintFastestLaps INTEGER DEFAULT 0,
    SeasonsRaced INTEGER DEFAULT 0,
    Points REAL DEFAULT 0,
    Starts INTEGER DEFAULT 0,
    Entries INTEGER DEFAULT 0,
    SprintStarts INTEGER DEFAULT 0,
    SprintEntries INTEGER DEFAULT 0,
    DNFs INTEGER DEFAULT 0,
    GrandPrixLapsLed INTEGER DEFAULT 0,
    SprintLapsLed INTEGER DEFAULT 0,
    BestGridPosition INTEGER,
    BestSprintGridPosition INTEGER,
    BestQualifyingPosition INTEGER,
    BestRacePosition INTEGER,
    BestSprintPosition INTEGER,
    BestSprintQualifyingPosition INTEGER,
    FirstGrandPrix TEXT,
    LastGrandPrix TEXT,
    ConstructorID INTEGER,
    FirstGrandPrixID INTEGER,
    LastGrandPrixID INTEGER,
    needstatsupdate BOOLEAN DEFAULT 0,
    FOREIGN KEY (ConstructorID) REFERENCES Constructors(ID),
    FOREIGN KEY (FirstGrandPrixID) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (LastGrandPrixID) REFERENCES GrandsPrix(ID)
)''')

cursor.execute('''CREATE TABLE EngineModels (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EngineMake TEXT,
    EngineModel TEXT UNIQUE,
    Wins INTEGER DEFAULT 0,
    Podiums INTEGER DEFAULT 0,
    Poles INTEGER DEFAULT 0,
    FastestLaps INTEGER DEFAULT 0,
    SprintWins INTEGER DEFAULT 0,
    SprintPodiums INTEGER DEFAULT 0,
    SprintPoles INTEGER DEFAULT 0,
    SprintFastestLaps INTEGER DEFAULT 0,
    SeasonsRaced INTEGER DEFAULT 0,
    Points REAL DEFAULT 0,
    Starts INTEGER DEFAULT 0,
    Entries INTEGER DEFAULT 0,
    SprintStarts INTEGER DEFAULT 0,
    SprintEntries INTEGER DEFAULT 0,
    DNFs INTEGER DEFAULT 0,
    GrandPrixLapsLed INTEGER DEFAULT 0,
    SprintLapsLed INTEGER DEFAULT 0,
    BestGridPosition INTEGER,
    BestSprintGridPosition INTEGER,
    BestQualifyingPosition INTEGER,
    BestRacePosition INTEGER,
    BestSprintPosition INTEGER,
    BestSprintQualifyingPosition INTEGER,
    FirstGrandPrix TEXT,
    LastGrandPrix TEXT,
    EngineMakeID INTEGER,
    FirstGrandPrixID INTEGER,
    LastGrandPrixID INTEGER,
    needstatsupdate BOOLEAN DEFAULT 0,
    FOREIGN KEY (EngineMakeID) REFERENCES Engines(ID),
    FOREIGN KEY (FirstGrandPrixID) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (LastGrandPrixID) REFERENCES GrandsPrix(ID)
)''')

cursor.execute('''CREATE TABLE GrandPrixResults (
    grandprix TEXT,
    number INTEGER,
    driver TEXT,
    nationality TEXT,
    team TEXT,
    constructor TEXT,
    chassis TEXT,
    engine TEXT,
    enginemodel TEXT,
    tyre TEXT,
    substituteorthirddriver BOOLEAN,
    qualifyingposition INTEGER,
    qualifyingtime TEXT,
    qualifyinggap TEXT,
    qualifyingtimeinseconds REAL,
    qualifyinggapseconds REAL,
    qualifyinginterval REAL,
    prequalifyingposition INTEGER,
    prequalifyingtime TEXT,
    prequalifyinggap TEXT,
    prequalifyinginterval REAL,
    prequalifyingtimeinseconds REAL,
    starting_grid_position INTEGER,
    gridpenalty TEXT,
    gridpenalty_reason TEXT,
    sprintstarting_grid_position INTEGER,
    sprintgridpenalty TEXT,
    sprintgridpenalty_reason TEXT,
    fastestlap INTEGER,
    fastestlapinseconds REAL,
    fastestlapgapinseconds REAL,
    fastestlapinterval REAL,
    fastestlap_time TEXT,
    fastestlap_gap TEXT,
    fastestlap_lap INTEGER,
    sprintfastestlap INTEGER,
    sprintfastestlapinseconds REAL,
    sprintfastestlapgapinseconds REAL,
    sprintfastestlapinterval REAL,
    sprintfastestlap_time TEXT,
    sprintfastestlap_gap TEXT,
    sprintfastestlap_lap INTEGER,
    qualifying2position INTEGER,
    qualifying2time TEXT,
    qualifying2gap REAL,
    qualifying2interval REAL,
    qualifying2timeinseconds REAL,
    qualifying2laps INTEGER,
    qualifying1position INTEGER,
    qualifying1time TEXT,
    qualifying1gap REAL,
    qualifying1interval REAL,
    qualifying1timeinseconds REAL,
    qualifying1laps INTEGER,
    qualifyinglaps INTEGER,
    qualifying3time TEXT,
    qualifying3gap REAL,
    qualifying3interval REAL,
    qualifying3timeinseconds REAL,
    sprint_qualifyingposition INTEGER,
    sprint_qualifying1time TEXT,
    sprint_qualifying2time TEXT,
    sprint_qualifying3time TEXT,
    sprint_qualifying1gap REAL,
    sprint_qualifying1interval REAL,
    sprint_qualifying2gap REAL,
    sprint_qualifying2interval REAL,
    sprint_qualifying3gap REAL,
    sprint_qualifying3interval REAL,
    sprint_qualifyinggap REAL,
    sprint_qualifyinginterval REAL,
    sprint_qualifying1timeinseconds REAL,
    sprint_qualifying2timeinseconds REAL,
    sprint_qualifying3timeinseconds REAL,
    sprint_qualifyinglaps INTEGER,
    sprint_qualifyingtime TEXT,
    sprint_qualifyingtimeinseconds REAL,
    warmupposition INTEGER,
    warmuptime TEXT,
    warmupgap TEXT,
    warmuptimeinseconds REAL,
    warmuplaps INTEGER,
    practice1position INTEGER,
    practice1time TEXT,
    practice1gap TEXT,
    practice1interval REAL,
    practice1timeinseconds REAL,
    practice1laps INTEGER,
    practice2position INTEGER,
    practice2time TEXT,
    practice2gap TEXT,
    practice2interval REAL,
    practice2timeinseconds REAL,
    practice2laps INTEGER,
    practice3position INTEGER,
    practice3time TEXT,
    practice3gap TEXT,
    practice3interval REAL,
    practice3timeinseconds REAL,
    practice3laps INTEGER,
    practice4position INTEGER,
    practice4time TEXT,
    practice4gap TEXT,
    practice4interval REAL,
    practice4timeinseconds REAL,
    practice4laps INTEGER,
    sprintposition INTEGER,
    sprintlaps INTEGER,
    sprinttime TEXT,
    sprintpoints REAL,
    sprintstatus TEXT,
    sprintstatusreason TEXT,
    sprinttimeinseconds REAL,
    sprintgap TEXT,
    sprintgapinseconds REAL,
    sprintinterval REAL,
    raceposition INTEGER,
    racelaps INTEGER,
    racetime TEXT,
    racepoints REAL,
    racestatus TEXT,
    racestatusreason TEXT,
    racetimeinseconds REAL,
    racegap TEXT,
    racegapinseconds REAL,
    raceinterval REAL,
    penalties TEXT,
    sprint_penalties TEXT,
    driverid INTEGER,
    teamid INTEGER,
    constructorid INTEGER,
    chassisid INTEGER,
    engineid INTEGER,
    enginemodelid INTEGER,
    tyreid INTEGER,
    grandprixid INTEGER,
    nationalityid INTEGER,
    FOREIGN KEY (driverid) REFERENCES Drivers(ID),
    FOREIGN KEY (teamid) REFERENCES Teams(ID),
    FOREIGN KEY (constructorid) REFERENCES Constructors(ID),
    FOREIGN KEY (chassisid) REFERENCES Chassis(ID),
    FOREIGN KEY (engineid) REFERENCES Engines(ID),
    FOREIGN KEY (enginemodelid) REFERENCES EngineModels(ID),
    FOREIGN KEY (tyreid) REFERENCES Tyres(ID),
    FOREIGN KEY (grandprixid) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (nationalityid) REFERENCES Nationalities(ID)
)''')

cursor.execute('''CREATE TABLE PitStopSummary (
    GrandPrix TEXT,
    Number INTEGER,
    Driver TEXT,
    Constructor TEXT,
    StopNumber INTEGER,
    Lap INTEGER,
    DurationSpentInPitLane TEXT,
    TimeInSeconds REAL,
    TimeOfDayStopped TEXT,
    TotalTimeSpentInPitLane TEXT,
    TotalTimeinSeconds REAL,
    DurationStoppedInPitBox REAL,
    type TEXT,
    GrandPrixID INTEGER,
    DriverID INTEGER,
    ConstructorID INTEGER,
    FOREIGN KEY (GrandPrixID) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (DriverID) REFERENCES Drivers(ID),
    FOREIGN KEY (ConstructorID) REFERENCES Constructors(ID)
)''')

cursor.execute('''CREATE TABLE LapByLap (
    GrandPrix TEXT,
    Driver TEXT,
    Position INTEGER,
    Lap INTEGER,
    Type TEXT,
    SafetyCar BOOLEAN,
    Time TEXT,
    TimeInSeconds REAL,
    TyreCompound TEXT,
    StintNumber INTEGER,
    Sector1Time REAL,
    Sector2Time REAL,
    Sector3Time REAL,
    TyreAge INTEGER,
    TrackStatus TEXT,
    QualifyingSegment TEXT,   
    GrandPrixID INTEGER,
    DriverID INTEGER,
    FOREIGN KEY (GrandPrixID) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (DriverID) REFERENCES Drivers(ID)
)''')

cursor.execute('''CREATE TABLE DriversChampionship (
    ID TEXT PRIMARY KEY,
    Season INTEGER,
    Position INTEGER,
    Driver TEXT,
    Points REAL,
    OutOf REAL,
    RaceByRace TEXT,
    DriverID INTEGER,
    FOREIGN KEY (DriverID) REFERENCES Drivers(ID)
)''')

cursor.execute('''CREATE TABLE ConstructorsChampionship (
    ID TEXT PRIMARY KEY,
    Season INTEGER,
    Position INTEGER,
    Constructor TEXT,
    Engine TEXT,
    Points REAL,
    OutOf REAL,
    RaceByRace TEXT,
    ConstructorID INTEGER,
    EngineID INTEGER,
    FOREIGN KEY (ConstructorID) REFERENCES Constructors(ID),
    FOREIGN KEY (EngineID) REFERENCES Engines(ID)
)''')

cursor.execute('''CREATE TABLE InSeasonProgressDrivers (
    GrandPrix TEXT,
    PositionAtThisPoint INTEGER,
    Driver TEXT,
    PointsAtThisPoint REAL,
    GrandPrixID INTEGER,
    DriverID INTEGER,
    FOREIGN KEY (GrandPrixID) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (DriverID) REFERENCES Drivers(ID)
)''')

cursor.execute('''CREATE TABLE InSeasonProgressConstructors (
    GrandPrix TEXT,
    PositionAtThisPoint INTEGER,
    Constructor TEXT,
    Engine TEXT,
    PointsAtThisPoint REAL,
    GrandPrixID INTEGER,
    ConstructorID INTEGER,
    EngineID INTEGER,
    FOREIGN KEY (GrandPrixID) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (ConstructorID) REFERENCES Constructors(ID),
    FOREIGN KEY (EngineID) REFERENCES Engines(ID)
)''')

cursor.execute('''CREATE TABLE Nationalities (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Nationality TEXT UNIQUE,
    FirstGrandPrix TEXT,
    LastGrandPrix TEXT,
    DriverCount INTEGER DEFAULT 0,
    Wins INTEGER DEFAULT 0,
    Podiums INTEGER DEFAULT 0,
    Poles INTEGER DEFAULT 0,
    FastestLaps INTEGER DEFAULT 0,
    SprintWins INTEGER DEFAULT 0,
    SprintPodiums INTEGER DEFAULT 0,
    SprintPoles INTEGER DEFAULT 0,
    SprintFastestLaps INTEGER DEFAULT 0,
    Championships INTEGER DEFAULT 0,
    SeasonsRaced INTEGER DEFAULT 0,
    Points REAL DEFAULT 0,
    Starts INTEGER DEFAULT 0,
    Entries INTEGER DEFAULT 0,
    SprintStarts INTEGER DEFAULT 0,
    SprintEntries INTEGER DEFAULT 0,
    DNFs INTEGER DEFAULT 0,
    GrandPrixLapsLed INTEGER DEFAULT 0,
    SprintLapsLed INTEGER DEFAULT 0,
    BestGridPosition INTEGER,
    BestSprintGridPosition INTEGER,
    BestQualifyingPosition INTEGER,
    BestRacePosition INTEGER,
    BestSprintPosition INTEGER,
    BestSprintQualifyingPosition INTEGER,
    FirstGrandPrixID INTEGER,
    LastGrandPrixID INTEGER,
    needstatsupdate BOOLEAN DEFAULT 0,
    FOREIGN KEY (FirstGrandPrixID) REFERENCES GrandsPrix(ID),
    FOREIGN KEY (LastGrandPrixID) REFERENCES GrandsPrix(ID)
)''')
cursor.execute('''CREATE TABLE RaceReports (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    GrandPrixName TEXT UNIQUE,
    RaceReport TEXT,
    FOREIGN KEY (ID) REFERENCES GrandsPrix(ID)
)''')

conn.commit()
conn.close()
print("Database reset and initialized.")
